# Generated by Django 4.0.4 on 2022-04-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='crated',
            new_name='created',
        ),
    ]
